### PR TITLE
Support 'second' as period for Rate Limiting

### PR DESCRIPTION
**Pull request by pzaleski**
The gateway currently supports only two periods for rate limiting: `minute` and `hour`, since rate limiting is implemented as sliding window in Skipper Ingress using a minute can be dangerous to use for high traffic applications. For example, if number of requests should be limited to 1000 requests per second, currently it needs to be set to 60,000 requests per minute, which in turns means in worst case client can make up to 60,000 requests per second.

### CODE REVIEW

**Comment by herojan** [comment]
:+1:

**Comment by irishshagua** [comment]
:+1:

**Comment by cjbooms** [comment]
Looks like the CDP build is not getting kicked off

**Comment by cjbooms** [comment]
👎

**Comment by cjbooms** [comment]
Adding veto until we can get CI to build

**Comment by cjbooms** [comment]
Moved to:
https://github.com/zalando-incubator/fabric-gateway/pull/82

**Pull request closed without merging**
