### PR TITLE
MID-2995: Test SAN self signed cert

### PR DESCRIPTION
**Pull request by irishshagua**
* Re-Generate certs with SAN
  * Update callback cert and re-set to Fail

Signed-off-by: bmooney <brian.mooney@zalando.ie>

### CODE REVIEW

**Comment by irishshagua** [comment]
👍

**Comment by herojan** [comment]
Is gateway-operator.jks empty? the diff says the file is empty

**Comment by irishshagua** [comment]
> Is gateway-operator.jks empty? the diff says the file is empty

Diff says Binary File not shown. It can't be empty or else the build and tests on Playground wouldn't work

**Comment by herojan** [comment]
👍

**Pull request merged**
